### ISSUE TITLE
Mongoose strict query warning

### ISSUE THREAD

**Issue by BioBoost** [vives-dust/framework#150]
Getting this warning in the backend.

```
(node:42) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
```

Needs to be investigated.

**Comment by noahdebaere** [comment]
Fixed the strictquery in the backend.

Found this error below as well:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/60788351/214823075-6dd1e18f-d3c2-414a-a017-fa07e796612c.png">

**Comment by noahdebaere** [comment]
The warning is not relevant anymore since we have already upgraded to mongoose 6.X

This issue can be closed with pr.
