### ISSUE TITLE
public friendly id's

### ISSUE THREAD

**Issue by sillevl** [vives-dust/framework#23]
Instead of using mongodb _id's in public endpoints it might be better to implement nanoid's <https://github.com/ai/nanoid> 

Mongodb id's still leak information about internal features that might be an surface to attack

**Comment by BioBoost** [comment]
Added hooks for the different public entities that inject "id" before create. Works like a charm. "id" is also made immutable in mongoose schema, which makes sure it cannot be changed anymore after being set. Doesn't throw exception when providedi, it's just being ignored. This will allow PUT and PATCH incoming data to contain id later on for management routes without the need for removing these before providing them to mongoose.

**Comment by noahdebaere** [comment]
Add the nanoid functionality to the pre-defined spaces by @BioBoost. The mongoDB now uses nanoids as public id's.
