### ISSUE TITLE
Influx queries in grafana show multiple results

### ISSUE THREAD

**Issue by sillevl** [vives-dust/framework#25]
![afbeelding](https://user-images.githubusercontent.com/979071/194137328-a349df40-8677-477e-bc8c-2d92374095fa.png)

**Comment by noahdebaere** [comment]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/60788351/194246014-2be1ebee-79b4-4e9c-9ebb-bd44eb1cab7e.png">

On 3/10/2022 around 2PM an update was passed or change was made to exclude the codingRate from the incoming data.

**Comment by noahdebaere** [comment]
<img width="924" alt="image" src="https://user-images.githubusercontent.com/60788351/194249327-94eca4e1-4210-4b2a-93ce-cf45d5d02839.png">

<img width="323" alt="image" src="https://user-images.githubusercontent.com/60788351/194249366-589a481c-0956-45e0-a6fc-d4e74d60c1ea.png">


Added a drop of the codingRate column to fix the issue
