### ISSUE TITLE
Migrate Weatherstation dashboard in Grafana to Flux queries

### ISSUE THREAD

**Issue by sillevl** [vives-dust/framework#26]
![afbeelding](https://user-images.githubusercontent.com/979071/194137536-549dec7c-8041-46de-b290-1a807e6337f3.png)

**Comment by noahdebaere** [comment]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/60788351/194262496-05d05e4a-aa8a-4d65-b2d5-39c441ab2958.png">

Rewrote the flux queries and added the new variable stationId
