### ISSUE TITLE
Migrate WeatherAPI dashboard in Grafana to Flux queries

### ISSUE THREAD

**Issue by sillevl** [vives-dust/framework#27]
![afbeelding](https://user-images.githubusercontent.com/979071/194137649-058fa842-6063-46de-8170-bd7e6c0886ee.png)

**Comment by noahdebaere** [comment]
<img width="921" alt="image" src="https://user-images.githubusercontent.com/60788351/194266171-7e913b93-0f92-4c6c-82cd-1532f6c9b4b5.png">

Made a WeatherAPI dashboard on Influx for internal purposes only.

**Comment by noahdebaere** [comment]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/60788351/194268717-f0a3281a-ea5f-4443-b7c9-28cb8a4734a0.png">

Added the flux queries for the WeatherAPI dashboard.
