### ISSUE TITLE
Grafana dashboard that correlates rain with moisture

### ISSUE THREAD

**Issue by sillevl** [vives-dust/framework#28]
Single graph with left and right axis
* left axis: Average moisture values (average of levels 1-4)
* right axis: daily rain (max values of the day) -> might be hard to visualize properly (aggregate over longer time?)

**Comment by noahdebaere** [comment]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/60788351/194291736-5fd2e7e9-96da-4e17-a2a0-692133c5eaae.png">

Correlation dashboard made on Grafana.
