### ISSUE TITLE
The api-docs will not build properly

### ISSUE THREAD

**Issue by noahdebaere** [vives-dust/framework#32]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/60788351/194546823-db6c3398-2e3b-4514-bfcb-cedd456560a1.png">

See error above

**Comment by BioBoost** [comment]
Build is ok. Problem is that path to spec file needs to be full url or local file. But when specifying local file it seems to be handled incorrectly when using docker.

It seems they have some docker image / configs: https://github.com/Redocly/redoc/tree/16f542bbfe856e5ae5eb40636ac79421fa2f397b/config/docker

**Comment by noahdebaere** [comment]
Issue fixed with pull request #39.
