### ISSUE TITLE
Adding the weatherstations to production

### ISSUE THREAD

**Issue by noahdebaere** [vives-dust/framework#85]
Creating the rest routes to add all of the weatherstations to the production environment.

**Comment by noahdebaere** [comment]
<img width="373" alt="image" src="https://user-images.githubusercontent.com/60788351/202694749-421de4d5-0bbe-4554-b42b-ada2427f18c0.png">


Routes are pushed to the [routes repo](https://github.com/vives-dust/secret-api-entitie-creation-requests/blob/main/routes-weatherstation.rest)

**Comment by noahdebaere** [comment]
@BioBoost will review them at his earliest convenience and implement them into the production environment.

**Comment by BioBoost** [comment]
Done
