### ISSUE TITLE
Backend crashes when testing locally

### ISSUE THREAD

**Issue by noahdebaere** [vives-dust/framework#86]
When testing some of the services and/or implementations the backend tends to crash. 

ERROR: 

> **[Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`](https://www.cnblogs.com/keRee/p/16719245.html)**

After searching for a solution for this problem, I found [this forum](https://www.cnblogs.com/keRee/p/16719245.html) that stated (after translation) that the TypeScript version was too high. After downgrading my TypeScript locally to version ~4.2.3 instead of version 4.9.3 the issue was resolved.

Is this a recurring problem?

**Comment by BioBoost** [comment]
We shouldn't downgrade ts but rather upgrade `ts-node` and alike. Problem is actually ts-node that is older version. We need to upgrade the `ts-node-dev` development dependency.

**Comment by BioBoost** [comment]
This seems to fix it `"ts-node-dev": "^2.0.0",`. Need to extra check it.
